name: "kelio-rewrite"
description: "Réécriture de l'apparence du site de badgeage à AG2R La Mondiale à usage privé\r\nExtensions utilisées : ViolentMonkey (https://addons.mozilla.org/fr/firefox/addon/violentmonkey/), Stylus (https://addons.mozilla.org/fr/firefox/addon/styl-us/?)"
topics: []
homepage: ""
source:
  provider: gitlab
  namespace: "sachahjkl"
  path: "sachahjkl/kelio-rewrite"
