name: CI

on:
  push:
    branches: ["**"]
    tags: ["**"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    name: Flake checks
    runs-on: [self-hosted, nixos]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: nix flake check --print-build-logs
